name: Test
"on":
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: lts/*
      - run: npm ci
      - run: npm run build
      - run: npm test
